### PR TITLE
First draft of HBNet page

### PR DESCRIPTION
**Pull request by JackMaguire**

### CODE REVIEW

**Comment by JackMaguire** [comment]
@kathyle9 Please let me know what you think of this when you get a chance. One section at the end depends on a feature that I only just added to Rosetta so I'll need to wait for the next version of PyRosetta to finish it.

**Comment by weitzner** [comment]
Hey Jack, is there a reason to interact with the internals of HBNet instead of setting up a mover with XML within PyRosetta? (examples can be found [here](https://github.com/RosettaCommons/pyrosettascripts_demo))

**Comment by JackMaguire** [comment]
@weitzner This is the first time I've used PyRosetta in years so I have no experience with that. I agree that it would make things easier. I'll give it a try

**Comment by JackMaguire** [comment]
@weitzner I followed your link and found a way to define an entire `"<ROSETTASCRIPTS/>"` tag, but is there also a way to do `my_mover = some_factory.foo('<HBNet option="True"/>')` ?

**Comment by jadolfbr** [comment]
Checkout the XmlObjects object that Brian Coventry wrote.

**Comment by klimaj** [comment]
> Checkout the XmlObjects object that Brian Coventry wrote.

```
my_mover = pyrosetta.rosetta.protocols.rosetta_scripts.XmlObjects.create_from_string("""
<MOVERS>
    <HBNet name="foo" option="True"/>
</MOVERS>
""").get_mover("foo")
```

This undergoes XML schema validation once, then apply: 
`my_mover.apply(pose)`

**Comment by ajasja** [comment]
@JackMaguire I guess you could also call `parse_my_tag` directly.

**Comment by weitzner** [comment]
I tend to prefer using the complete RosettaScripts tag via the distributed layer because the objects are readily serializable using dask, which is awesome. If you wanted to make a one-off mover, we could add some convenience functions to make the full tag.

**Pull request merged**
