### PR TITLE
Update RS in PyRosetta to reflect recent changes to the core code 

### PR DESCRIPTION
**Pull request by jadolfbr**
that basically broke this notebook. Remove the debug blocks around the core code so this can actually be tested properly.

### CODE REVIEW

**Comment by ajasja** [comment]
Not directly connected, but why does 
`parser.generate_mover(pose, "inputs/min_L1.xml")` need the pose?

Also, should we mention the `rosetta_scripts.SingleoutputRosettaScriptsTask` and `rosetta_scripts.MultipleoutputRosettaScriptsTask` in this notebook?

**Review by ajasja — APPROVED** [review]
LGTM.

**Comment by jadolfbr** [comment]
Good catch.  That was an error on my part. For those others, I've never used them, so I don't know how they work or what they are used for.

**Comment by ajasja** [comment]
Sounds good! It was also a question for @klimaj, who I think uses SingleoutputRosettaScriptsTask regulary:) 
I can also add an example (in a different PR)

**Comment by klimaj** [comment]
@ajasja I agree, it's worth mentioning `SingleoutputRosettaScriptsTask` and `MultioutputRosettaScriptsTask` classes in `02.07`, perhaps with markdown `Note: This Jupyter notebook requires the PyRosetta distributed layer.` (e.g., as in `08.02`, `16.05`) since these should require the serialization build of PyRosetta which users may not have set up.

**Comment by jadolfbr** [comment]
Ok, I fixed this and also fixed two unit tests. I'll queue the tests, merge, and put the pointer here for main.  @klimaj @ajasja  - perhaps another notebook would be good to mention these since they take the distributed layer?

**Pull request merged**
