### PR TITLE
Add PyRosettaCluster tutorials

### PR DESCRIPTION
**Pull request by klimaj**
This PR aims to:

- Add five Jupyter Lab tutorials for PyRosettaCluster usage into Chapter 16 (chapters 16.06-16.10)
  - PyRosettaCluster is a class for reproducible, high-throughput job distribution of user-defined PyRosetta protocols efficiently parallelized on the user's local computer, high-performance computing (HPC) cluster, or elastic cloud computing infrastructure with available compute resources.
- Update `notebooks/environment.yml` to include third-party package dependencies and latest `pyrosetta` version supporting PyRosettaCluster
- Update notebook metadata by `cd notebooks && nbgrader update . && cd ..`
- Remove deprecation warning in `make-student-np.bash` script, bypass `header.ipynb` and `cp` errors, and run `make-student-np.bash`

### CODE REVIEW

**Comment by kathyle9** [comment]
Possibly minor thing: I think something happened when make-student script was run? Some of the notebooks in student-notebook are missing (2.0x, 3.0x, etc).

**Comment by klimaj** [comment]
Thanks @kathyle9 , great catch! Upon running `./make-student-nb.bash`, on those notebooks specifically I was receiving the error, for example:
```
[DbAssignmentAddApp | INFO] Creating/updating assignment with ID '14.00-RNA-Basics': {'duedate': None}
[GenerateAssignmentApp | INFO] Updating/creating assignment '14.00-RNA-Basics': {}
[GenerateAssignmentApp | INFO] Converting notebook /Users/Jason_iMac/git/PyRosetta.notebooks/student-notebooks/source/./14.00-RNA-Basics/14.00-RNA-Basics.ipynb
[GenerateAssignmentApp | ERROR] One or more notebooks in the assignment use an old version
    of the nbgrader metadata format. Please **back up your class files
    directory** and then update the metadata using:

    nbgrader update .
```
I ran `cd notebooks && nbgrader update . && cd ..` to update the notebook metadata, and then re-ran `./make-student-nb.bash`. That fixed the error for all but one notebook in the `student-notebooks` directory! I only got an error for Chapter `15.01-Accounting-for-the-lipid-bilayer`, which did not generate a student notebook:

```
    RuntimeError: Solution region detected in a non-solution cell; please make sure all solution regions are within solution cells.

[GenerateAssignmentApp | ERROR] There was an error processing assignment '15.01-Accounting-for-the-lipid-bilayer' for student '.'
[GenerateAssignmentApp | ERROR] Please see the the above traceback for details on the specific errors on the above failures.
```

**Comment by kathyle9** [comment]
Fixed some metadata issue. Should work now. I'm sorry I might have made this system more complicated than it has to be

**Comment by klimaj** [comment]
@kathyle9 thank you for fixing the 15.01 notebook! `make-student-nb.bash` now generates the student notebooks.

I received a couple of errors upon running `./make-student-nb.bash`:
```
[DbAssignmentAddApp | INFO] Creating/updating assignment with ID 'header.ipynb': {'duedate': None}
[GenerateAssignmentApp | WARNING] No notebooks were matched by '~/git/PyRosetta.notebooks/student-notebooks/source/./header.ipynb/*.ipynb'
[GenerateAssignmentApp | ERROR] No notebooks were matched by '~/git/PyRosetta.notebooks/student-notebooks/source/./header.ipynb'
[GenerateAssignmentApp | ERROR] Did you mean: ~/git/PyRosetta.notebooks/student-notebooks/source/./header.ipynb
```
and a `cp` error. I've pushed fixes to `make-student-nb.bash` to bypass the errors.

**Comment by kathyle9** [comment]
Thanks!

**Review by kathyle9 — APPROVED** [review]

**Pull request merged**
