### PR TITLE
Adding A NNK Scan Section 6.08 to The Notebook

### PR DESCRIPTION
**Pull request by yuanhan-wu-kulplab**
This NNK Scan code is developed and used in the Kulp lab. It was simplified for teaching purpose for the notebook but keeps as much details as possible. It represents our typical work flow with filtering conditions and a heatmap generator.

### CODE REVIEW

**Comment by jadolfbr** [comment]
Awesome.  I'll check it through. You don't need to open a new PR, just push your changes here.

**Comment by jadolfbr** [comment]
Can you check again, I'm still seeing the same notebook: https://github.com/RosettaCommons/PyRosetta.notebooks/blob/918a26b568ba22ab01d1184f1d487a784caaf882/notebooks/06.08-Point-Mutation-Scan.ipynb

**Comment by jadolfbr** [comment]
Something is wonky with GitHub.  I can see the changes in the commit, but they are not showing up in the 'changed files' tab, or when I 'view file' in that tab

**Comment by yuanhan-wu-kulplab** [comment]
Hi Jared @jadolfbr ! I think I uploaded it to the input folder by accident, now it's in its correct place.

**Comment by jadolfbr** [comment]
This looks much better!  A few notes.  I'll be able to work through this in the next day or two. 
1) References - include any papers where this protocol was used. 
2) We'll need to add debug statements to not run long-running parts on the test server.  The limitations for timeout on the test server are pretty short, unfortunately, so we'll need to wrap longer bits in this for example:

```
if not os.getenv("DEBUG"):
    packer.apply(pose)
```

3) For the analysis, we'll need to make sure that the notebook environment and the setup docs have the libraries you are using.  I'm honestly not sure exactly what they are - is this R with Python or an R-like python module?  If this is the former, we will need to figure out how to match the dependancies in such a way as to be able to run it properly.

**Comment by yuanhan-wu-kulplab** [comment]
@jadolfbr The rpy2 is a python module for running R in python basically. The rpy2.ipython package supports R's functionality in ipython notebook. https://rpy2.readthedocs.io/en/latest/

For the reference, we are using a multilayer stacked version of this to design an antibody at the moment and potentially other projects happening now. But they are not yet published.

**Comment by yuanhan-wu-kulplab** [comment]
@jadolfbr Also, I will try to add those debug lines and you can probably review them later!

**Comment by yuanhan-wu-kulplab** [comment]
Hi Jared @jadolfbr , I just add the test server line. I think simply adding it to the "pack" function is enough, since it is the most time constrained one. We might not need to wrap the whole "for loop" stuff with the env? or we do. Please let me know!

**Comment by ajasja** [comment]
> 3. For the analysis, we'll need to make sure that the notebook environment and the setup docs have the libraries you are using.  I'm honestly not sure exactly what they are - is this R with iPython (an R code block) or an R-like python module?  If this is the former, we will need to figure out how to match the dependancies in such a way as to be able to run it properly.

The heat map would be super easy to do with matplotlib (and perhaps seaborn) if that makes installation/testing easier. 

(I could probably do it in about half an hour if you like) @yuanhan-wu-kulplab @jadolfbr

**Comment by yuanhan-wu-kulplab** [comment]
@ajasja Hi Ajasja, that would be really helpful! It would be great if you can help to get a heatmap with python module and if that's not too much a burden for you. Thank you so much for offering your help! There is a sample input file (note_output.csv) for generating heat map in the "\notebook\inputs" folder. If you don't have time for this I can probably learn about the module and draw a map too.

**Comment by ajasja** [comment]
Sounds good, I'm on it.

**Comment by ajasja** [comment]
@yuanhan-wu-kulplab My R is a bit rusty, but I have more positions than in the original image. Am I filtering in a wrong way, or should I average something?
image

Link to notebook [here ](https://github.com/yuanhan-wu-kulplab/PyRosetta.notebooks/blob/662322ef35db07ca8b047cf083147a2f851ded95/notebooks/06.08-Point-Mutation-Scan.ipynb)
(Sorry I pushed to your fork instead of mine by mistake, not sure how I even have access:)

**Comment by yuanhan-wu-kulplab** [comment]
@ajasja Hi Ajasja, thanks for the work! It's normal to have more positions, because I purposefully select fewer positions to reduce time in the for loop. So that's totally fine and you are free to adjust the color. A white to red may not be the best scale I just happen to use it.

**Comment by yuanhan-wu-kulplab** [comment]
We did not expect the sample to match and we should probably fix that. So do not worry about the differences. If you want to test your map, you can walk through the section to get an output file and test whether two maps match. Thanks for your work again!

**Comment by ajasja** [comment]
@yuanhan-wu-kulplab I polished the heat map a little bit. Hope you like it. Let me know if I should change anything. 
With a little stricter filtering on the RATIO the heat-map looks much better.

PS: you probably know this, but you can replace 
```
cmd = "cat *csv > test_output.csv"
os.system(cmd)
```
with
`!cat *csv > test_output.csv`

**Comment by yuanhan-wu-kulplab** [comment]
@ajasja That looks pretty nice! Thank you so much. I think the coolwarm color looks better for the heatmap, I can change it by myself. Thanks for your help!

**Comment by yuanhan-wu-kulplab** [comment]
@jadolfbr Hi Jared, thanks to Ajasja, we updated the heatmap without the burden of installing R packages, I wrapped the packing and the for loop with the debug condition. Could you check whether this is good to go? Thank you so much for your help!

**Comment by jadolfbr** [comment]
Awesome.  I’m about to move out of state tomorrow, but I’ll try to get to it by the end of the day - if not, early next week.

**Comment by yuanhan-wu-kulplab** [comment]
@jadolfbr Thanks a lot. Safe trip and have a good weekend!

**Comment by jadolfbr** [comment]
I have been through the notebook, and refactored/fixed quite a bit.  I would not use changing directories in a  notebook context.  Since debugging block-per-block, this can easily lead to errors.  In general, changing directories in python should probably only be done sparingly.  In all, the tutorial looks very good.  I have also added some comments here and there.  The speed should be fine on the test server, and I believe this is ready to merge.  Please take a look at my changes and let me know if anything is amiss.  Thanks for adding this!  Cheers!

**Comment by yuanhan-wu-kulplab** [comment]
@jadolfbr Thanks Jared! It's my honor to contribute!

**Pull request merged**
